services:
  backend:
    container_name: temporary-contacts-backend
    build:
      context: ./backend
    image: temporary-contacts-backend:latest
    environment:
      PORT: "4000"
      NODE_ENV: production
    volumes:
      - ./backend/data:/app/data
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    container_name: temporary-contacts-frontend
    image: temporary-contacts-frontend:latest
    build:
      context: ./frontend
      args:
        # VITE_API_URL: http://YOUR_HOST_IP:4000
        VITE_API_URL: http://<host-ip>:4000  # DX: MAKE SURE TO UPDATE THE LOCAL IP
    environment:
      - VITE_API_URL=http://<host-ip>:4000 # DX: MAKE SURE TO UPDATE THE LOCAL IP
    depends_on:
      - backend
    ports:
      - "5173:4173"
    restart: unless-stopped

    #for ip=  hostname -I
